#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : myst-parser
Version  : 0.15.2
Release  : 1
URL      : https://files.pythonhosted.org/packages/91/33/e2ff1d4675d9f6fae51e03b0ad99ab9276773424006191c1057609b543db/myst-parser-0.15.2.tar.gz
Source0  : https://files.pythonhosted.org/packages/91/33/e2ff1d4675d9f6fae51e03b0ad99ab9276773424006191c1057609b543db/myst-parser-0.15.2.tar.gz
Summary  : An extended commonmark compliant parser, with bridges to docutils & sphinx.
Group    : Development/Tools
License  : MIT
Requires: myst-parser-bin = %{version}-%{release}
Requires: myst-parser-license = %{version}-%{release}
Requires: myst-parser-python = %{version}-%{release}
Requires: myst-parser-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(beautifulsoup4)
BuildRequires : pypi(coverage)
BuildRequires : pypi(docutils)
BuildRequires : pypi(ipython)
BuildRequires : pypi(jinja2)
BuildRequires : pypi(pyyaml)
BuildRequires : pypi(setuptools)
BuildRequires : pypi(sphinx)
BuildRequires : pypi(wheel)

%description
[![Github-CI][github-ci]][github-link]
        [![Coverage Status][codecov-badge]][codecov-link]
        [![Documentation Status][rtd-badge]][rtd-link]

%package bin
Summary: bin components for the myst-parser package.
Group: Binaries
Requires: myst-parser-license = %{version}-%{release}

%description bin
bin components for the myst-parser package.


%package license
Summary: license components for the myst-parser package.
Group: Default

%description license
license components for the myst-parser package.


%package python
Summary: python components for the myst-parser package.
Group: Default
Requires: myst-parser-python3 = %{version}-%{release}

%description python
python components for the myst-parser package.


%package python3
Summary: python3 components for the myst-parser package.
Group: Default
Requires: python3-core
Provides: pypi(myst_parser)
Requires: pypi(docutils)
Requires: pypi(jinja2)
Requires: pypi(markdown_it_py)
Requires: pypi(mdit_py_plugins)
Requires: pypi(pyyaml)
Requires: pypi(sphinx)

%description python3
python3 components for the myst-parser package.


%prep
%setup -q -n myst-parser-0.15.2
cd %{_builddir}/myst-parser-0.15.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1637343943
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/myst-parser
cp %{_builddir}/myst-parser-0.15.2/LICENSE %{buildroot}/usr/share/package-licenses/myst-parser/ab5a711cce75e49bdbd08bbcb728262e30580e5d
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/myst-anchors

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/myst-parser/ab5a711cce75e49bdbd08bbcb728262e30580e5d

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
